const demoProjects=[
 {title:'Juveniles',category:'shortfilms',type:'Short Film',ratio:'landscape',src:'assets/videos/juveniles.mp4',poster:''},
 {title:'Automobile Advertisement',category:'ads',type:'Ad / Advertisement',ratio:'landscape',src:'assets/videos/automobile-ad.mp4',poster:''},
 {title:'Travel Reel',category:'reels',type:'Instagram Reel',ratio:'vertical',src:'assets/videos/travel-reel.mp4',poster:''},
 {title:'Wedding Invitation',category:'reels',type:'Instagram Reel',ratio:'vertical',src:'assets/videos/wedding-invitation.mp4',poster:''},
 {title:'Company Promotion',category:'company',type:'Corporate / Company',ratio:'landscape',src:'assets/videos/company-promo.mp4',poster:''}
];
function nav(){const btn=document.querySelector('.menu-btn'), links=document.querySelector('.navlinks');if(btn)btn.onclick=()=>links.classList.toggle('open')}
function teamModal(){const modal=document.querySelector('#teamModal');if(!modal)return;document.querySelectorAll('[data-team]').forEach(c=>c.onclick=()=>{modal.querySelector('img').src=c.dataset.photo;modal.querySelector('.modal-name').textContent=c.dataset.name;modal.querySelector('.modal-role').textContent=c.dataset.role;modal.querySelector('.modal-description').textContent=c.dataset.description;modal.classList.add('open');document.body.style.overflow='hidden'});modal.addEventListener('click',e=>{if(e.target===modal||e.target.closest('.modal-close')){modal.classList.remove('open');document.body.style.overflow=''}})}
function renderWork(filter='all'){const grid=document.querySelector('#workGrid');if(!grid)return;let projects=[...demoProjects];try{const saved=JSON.parse(localStorage.getItem('kalyanProjects')||'[]');projects=saved.length?saved:projects}catch(e){}grid.innerHTML='';const shown=projects.filter(p=>filter==='all'||p.category===filter);if(!shown.length){grid.innerHTML='<div class="card-empty">No projects in this category yet. Add videos from the client dashboard.</div>';return}shown.forEach(p=>{const card=document.createElement('article');card.className='work-card '+(p.ratio==='landscape'?'wide':'');card.dataset.category=p.category;card.innerHTML=`<div class="work-media ${p.ratio}">${p.src?`<video controls preload="metadata" playsinline ${p.poster?`poster="${p.poster}"`:''}><source src="${p.src}" type="video/mp4"></video>`:`<div style="height:100%;display:grid;place-items:center;color:#aaa">VIDEO</div>`}</div><div class="work-info"><div class="work-meta"><span>${p.type}</span><span>${p.ratio==='vertical'?'9:16':p.ratio==='square'?'1:1':'16:9'}</span></div><h3>${p.title}</h3></div>`;grid.appendChild(card)})}
function filters(){document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderWork(b.dataset.filter)})}
function showreel(){const c=document.querySelector('#reelCanvas');if(!c)return;const ctx=c.getContext('2d');let start=performance.now();const scenes=[['KALYAN','CHITTETI','VISUAL STORYTELLER'],['EDIT.','GRADE.','CREATE.'],['VIDEO','EDITOR','COLORIST / DI ARTIST'],['FRAME.','LIGHT.','MOTION / STORY / SOUND'],['VISUAL','STORIES.','THAT WORK.']];function resize(){const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d}resize();addEventListener('resize',resize);function draw(now){const t=Math.min((now-start)/1000,20),w=c.clientWidth,h=c.clientHeight,d=devicePixelRatio||1;ctx.setTransform(d,0,0,d,0,0);const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#292929');g.addColorStop(.55,'#050505');g.addColorStop(1,'#242424');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(let i=0;i<12;i++){let x=((i*180+t*35)%(w+220))-110;ctx.fillStyle='rgba(255,255,255,.035)';ctx.fillRect(x,0,80,h)}ctx.strokeStyle='rgba(255,255,255,.08)';for(let y=h*.72;y<h;y+=24){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const s=scenes[Math.min(4,Math.floor(t/4))],local=(t%4)/4,a=Math.min(1,local/.18,(1-local)/.18);ctx.globalAlpha=a;ctx.fillStyle='#fff';ctx.font=`800 ${Math.max(40,w*.075)}px Anton`;ctx.fillText(s[0],w*.07,h*.43);ctx.fillStyle='#ddd';ctx.font=`800 ${Math.max(28,w*.052)}px Anton`;ctx.fillText(s[1],w*.07,h*.43+Math.max(48,w*.072));ctx.fillStyle='#999';ctx.font='12px DM Mono';ctx.fillText(s[2],w*.07,h*.43+Math.max(82,w*.11));ctx.globalAlpha=1;ctx.fillStyle='#aaa';ctx.fillText('KC  |  KALYAN CHITTETI',w*.04,h*.08);ctx.fillText(`00:${String(Math.floor(t)).padStart(2,'0')} / 00:20`,w*.83,h*.08);ctx.fillStyle='#fff';ctx.fillRect(w*.05,h*.92,w*.9*(t/20),2);if(t<20)requestAnimationFrame(draw)}requestAnimationFrame(draw)}
function admin(){const login=document.querySelector('#loginForm');const panel=document.querySelector('#adminPanel');if(!login||!panel)return;login.onsubmit=e=>{e.preventDefault();const u=document.querySelector('#adminUser').value,p=document.querySelector('#adminPass').value;if(u==='admin'&&p==='kalyan123'){document.querySelector('.login').classList.add('hidden');panel.classList.remove('hidden')}else alert('Demo login: admin / kalyan123')};const add=document.querySelector('#addProject');add.onclick=()=>{const p={title:document.querySelector('#pTitle').value,category:document.querySelector('#pCategory').value,type:document.querySelector('#pType').value,ratio:document.querySelector('#pCategory').value==='reels'?'vertical':'landscape',src:document.querySelector('#pSrc').value};const arr=JSON.parse(localStorage.getItem('kalyanProjects')||'[]');arr.push(p);localStorage.setItem('kalyanProjects',JSON.stringify(arr));alert('Project saved in this browser. For real client uploads, connect this dashboard to a server/database.');document.querySelector('#pTitle').value='';document.querySelector('#pSrc').value=''} }
nav();teamModal();filters();renderWork();showreel();admin();
